'use client';
import {useMemo,useState} from 'react';
import {importedQuestions,Question} from './questions';

type View='questoes'|'prova'|'cadastro'|'roteiros';
const topicIcons:Record<string,string>={'Mecânica':'↗','Eletricidade':'ϟ','Eletrostática':'⊕','Eletromagnetismo':'∿','Óptica':'◈','Termologia':'♨','Gravitação':'◎','Oscilações':'∿','Ondulatória':'≈','Fluidos':'≋','Física moderna':'ℏ','Física geral':'Σ'};

export default function Home(){
 const[questions,setQuestions]=useState<Question[]>(importedQuestions);const[active,setActive]=useState(importedQuestions[0]);const[choice,setChoice]=useState<number|null>(null);const[checked,setChecked]=useState(false);const[topic,setTopic]=useState('Todos');const[year,setYear]=useState('Todos');const[query,setQuery]=useState('');const[view,setView]=useState<View>('questoes');const[selected,setSelected]=useState<number[]>(importedQuestions.slice(0,3).map(q=>q.id));const[showSource,setShowSource]=useState(false);const[scriptQuestion,setScriptQuestion]=useState(importedQuestions[0].id);
 const topics=useMemo(()=>Array.from(new Set(questions.map(q=>q.topic))),[questions]);
 const years=useMemo(()=>Array.from(new Set(questions.map(q=>q.year))).sort((a,b)=>b-a),[questions]);
 const filtered=useMemo(()=>questions.filter(q=>(year==='Todos'||String(q.year)===year)&&(topic==='Todos'||q.topic===topic)&&(q.title+q.text+q.code).toLowerCase().includes(query.toLowerCase())),[questions,topic,year,query]);
 const roteiro=questions.find(q=>q.id===scriptQuestion)??questions[0];
 function navigate(next:View){setView(next);setShowSource(false)}
 function openQuestion(q:Question){setActive(q);setChoice(null);setChecked(false);setShowSource(false);setView('questoes')}
 function downloadText(filename:string,content:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));a.download=filename;a.click();URL.revokeObjectURL(a.href)}
 function downloadQuestion(q:Question){downloadText(`${q.year}-ita-q${q.number}.txt`,`${q.code}\n${q.title}\nFonte: ${q.sourceFile}, página ${q.sourcePage}\n\n${q.text}\n\n${q.options.map((o,i)=>`${String.fromCharCode(65+i)}) ${o}`).join('\n')}`)}
 function roteiroText(q:Question){const resposta=q.answerLabel??'Questão anulada';return `ROTEIRO DE RESOLUÇÃO — ${q.code}\n${q.title}\n\n1. ABERTURA (0:00–0:15)\nHoje vamos resolver a questão ${q.number} de Física do ITA ${q.year}. Pause o vídeo, tente primeiro e depois acompanhe a resolução.\n\n2. LEITURA E DADOS (0:15–1:00)\n${q.text}\n\nDados e figura: consultar ${q.sourceFile}, página ${q.sourcePage}.\n\n3. IDEIA FÍSICA CENTRAL (1:00–1:40)\nTema: ${q.topic}. Apresente o princípio físico, as hipóteses e as grandezas relevantes antes das contas.\n\n4. RESOLUÇÃO PASSO A PASSO (1:40–5:00)\n• Organize os dados e converta unidades.\n• Escreva as equações fundamentais.\n• Desenvolva a solução com uma justificativa por etapa.\n• Compare o resultado com as alternativas.\n\n5. RESPOSTA (5:00–5:20)\nGabarito oficial: ${resposta}. Explique por que esta alternativa é compatível com o resultado.\n\n6. FECHAMENTO (5:20–5:35)\nSe esta resolução ajudou, salve a questão e pratique outros itens de ${q.topic}.\n\nTÍTULO SUGERIDO PARA O YOUTUBE\n${q.code}: ${q.title} | Resolução completa\n\nDESCRIÇÃO SUGERIDA\nResolução comentada da ${q.code}, tema ${q.topic}. Prova: ${q.sourceFile}.`}
 function addQuestion(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const newId=Date.now();const answer=Number(fd.get('answer'));const q:Question={id:newId,code:String(fd.get('code')),year:Number(fd.get('year')),number:Number(fd.get('number')),topic:String(fd.get('topic')),level:String(fd.get('level')),title:String(fd.get('title')),text:String(fd.get('text')),options:['a','b','c','d','e'].map(k=>String(fd.get(k))),answer,answerLabel:String.fromCharCode(65+answer),status:'Cadastro manual',video:String(fd.get('video')||''),scriptStatus:'Pendente',sourcePage:Number(fd.get('page')||0),sourceFile:String(fd.get('source')||'Cadastro manual'),sourceImage:'',essentialFigure:false};setQuestions(v=>[q,...v]);openQuestion(q)}
 return <main><header className="topbar"><button className="brand" onClick={()=>navigate('questoes')}><span>φ</span><strong>Física<br/><em>Resolvida</em></strong></button><nav><button className={view==='questoes'?'on':''} onClick={()=>navigate('questoes')}>Banco de questões</button><button className={view==='prova'?'on':''} onClick={()=>navigate('prova')}>Gerador de provas</button><button className={view==='roteiros'?'on':''} onClick={()=>navigate('roteiros')}>Roteiros</button><button className={view==='cadastro'?'on':''} onClick={()=>navigate('cadastro')}>Cadastrar</button></nav><button className="profile">WP</button></header>
 {view==='questoes'&&<div className="workspace"><aside className="filters"><p className="eyebrow">ACERVO OFICIAL</p><h2>Questões de Física</h2><div className="search"><span>⌕</span><input aria-label="Buscar questões" placeholder="Buscar questão..." value={query} onChange={e=>setQuery(e.target.value)}/></div><p className="label">PROVA</p><select className="year-select" aria-label="Filtrar por ano" value={year} onChange={e=>setYear(e.target.value)}><option>Todos</option>{years.map(y=><option key={y} value={y}>ITA {y}</option>)}</select><p className="label">ASSUNTO</p><button className={topic==='Todos'?'filter active':'filter'} onClick={()=>setTopic('Todos')}><span>◎</span>Todos<b>{questions.length}</b></button>{topics.map(t=><button key={t} className={topic===t?'filter active':'filter'} onClick={()=>setTopic(t)}><span>{topicIcons[t]||'•'}</span>{t}<b>{questions.filter(q=>q.topic===t).length}</b></button>)}<div className="generator-card"><span>✦</span><h3>{questions.length} questões importadas</h3><p>ITA {years.at(-1)}–{years[0]} com gabaritos oficiais e páginas de origem.</p><button onClick={()=>navigate('prova')}>Criar atividade →</button></div></aside>
 <section className="question"><div className="crumb">ITA {active.year} <span>/</span> FÍSICA <span>/</span> QUESTÃO {active.number}</div><div className="chips"><span>{active.code}</span><span className="level">● {active.level}</span><span className={active.status==='Anulada'?'annulled':'imported'}>{active.status==='Anulada'?'ANULADA':'✓ GABARITO CONFERIDO'}</span></div><h1>{active.title}</h1><p className="statement">{active.text}</p>{active.sourceImage&&<button className="source-toggle" onClick={()=>setShowSource(v=>!v)}>{showSource?'Fechar página original':'▣ Ver página original'} <small>p. {active.sourcePage}</small></button>}{showSource&&<div className="source-panel"><img src={active.sourceImage} alt={`Página ${active.sourcePage} da prova ITA ${active.year}`}/><p>Fonte: {active.sourceFile}, página {active.sourcePage}. Use esta imagem para conferir figuras, gráficos e a notação original.</p></div>}<div className="answers">{active.options.map((o,i)=><button key={`${i}-${o}`} onClick={()=>{setChoice(i);setChecked(false)}} className={`${choice===i?'chosen':''} ${checked&&active.answer===i?'correct':''} ${checked&&active.answer!==null&&choice===i&&i!==active.answer?'wrong':''}`}><b>{String.fromCharCode(65+i)}</b><span>{o}</span>{checked&&active.answer===i&&<i>✓</i>}</button>)}</div><div className="actions"><button className="primary" disabled={choice===null&&active.answer!==null} onClick={()=>setChecked(true)}>{active.answer===null?'Ver situação oficial':'Verificar resposta'}</button><button onClick={()=>downloadQuestion(active)}>⇩ Baixar questão</button>{active.video?<a href={active.video} target="_blank" rel="noreferrer">▶ Ver resolução</a>:<button onClick={()=>{setScriptQuestion(active.id);navigate('roteiros')}}>✎ Criar roteiro</button>}</div>{checked&&<div className={active.answer===null?'feedback annulled-box':choice===active.answer?'feedback good':'feedback'}><strong>{active.answer===null?'Questão anulada pelo gabarito oficial.':choice===active.answer?'Muito bem! Resposta correta.':'Ainda não. Revise a estratégia.'}</strong><span>{active.answer===null?'O ITA considerou a questão correta para todos os candidatos.':`Gabarito oficial: alternativa ${active.answerLabel}.`}</span></div>}</section>
 <aside className="list"><div className="list-head"><span>{filtered.length} questões</span><small>2026 → 2025</small></div>{filtered.map(q=><button key={q.id} className={q.id===active.id?'qcard active':'qcard'} onClick={()=>openQuestion(q)}><div><span>{q.code}</span><i>{q.status==='Anulada'?'Anulada':q.level}</i></div><strong>{q.title}</strong><p>{q.text}</p><small>{q.topic}<b>→</b></small></button>)}</aside></div>}
 {view==='prova'&&<section className="page"><div className="page-title"><p className="eyebrow">GERADOR DE ATIVIDADES</p><h1>Monte uma prova com questões reais.</h1><p>Selecione itens do ITA 2026 e 2025 e imprima uma folha organizada.</p></div><div className="builder"><div className="pick"><h2>Escolha as questões <span>{selected.length} selecionadas</span></h2>{questions.map(q=><label key={q.id}><input type="checkbox" checked={selected.includes(q.id)} onChange={()=>setSelected(s=>s.includes(q.id)?s.filter(x=>x!==q.id):[...s,q.id])}/><div><small>{q.code} · {q.topic}</small><strong>{q.title}</strong></div></label>)}</div><div className="paper"><div className="paper-head"><span>FÍSICA RESOLVIDA</span><strong>LISTA DE EXERCÍCIOS</strong><p>Nome: ___________________________________ Turma: __________</p></div>{questions.filter(q=>selected.includes(q.id)).map((q,n)=><article key={q.id}><b>{n+1}.</b><div><small>{q.code}</small><p>{q.text}</p>{q.options.map((o,i)=><span key={`${i}-${o}`}>({String.fromCharCode(65+i)}) {o}</span>)}</div></article>)}<button className="primary no-print" onClick={()=>window.print()}>⎙ Imprimir / salvar em PDF</button></div></div></section>}
 {view==='roteiros'&&<section className="page scripts-page"><div className="page-title"><p className="eyebrow">ESTÚDIO DE CONTEÚDO</p><h1>Roteiros para as resoluções.</h1><p>Escolha uma questão e gere uma estrutura pronta para adaptar à sua gravação.</p></div><div className="builder"><div className="pick"><h2>Fila de gravação <span>{questions.length} pendentes</span></h2>{questions.map(q=><button key={q.id} className={roteiro.id===q.id?'script-item active':'script-item'} onClick={()=>setScriptQuestion(q.id)}><small>{q.code} · {q.topic}</small><strong>{q.title}</strong><i>Roteiro pendente</i></button>)}</div><article className="script-paper"><div className="script-head"><span>ROTEIRO DE RESOLUÇÃO</span><strong>{roteiro.code}</strong><h2>{roteiro.title}</h2></div><pre>{roteiroText(roteiro)}</pre><div className="script-actions"><button className="primary" onClick={()=>downloadText(`roteiro-${roteiro.year}-q${roteiro.number}.txt`,roteiroText(roteiro))}>⇩ Baixar roteiro</button><button onClick={()=>openQuestion(roteiro)}>Ver questão</button></div></article></div></section>}
 {view==='cadastro'&&<section className="page"><div className="page-title"><p className="eyebrow">ÁREA DO PROFESSOR</p><h1>Cadastre uma nova questão.</h1><p>Adicione enunciado, alternativas, origem e o vídeo da resolução.</p></div><form className="form" onSubmit={addQuestion}><div className="grid"><label>Código / origem<input required name="code" placeholder="Ex.: ITA 2026 · Q13"/></label><label>Título<input required name="title" placeholder="Título curto da questão"/><input type="hidden" name="year" value="2026"/><input type="hidden" name="number" value="0"/></label><label>Assunto<select name="topic">{topics.map(t=><option key={t}>{t}</option>)}</select></label><label>Dificuldade<select name="level"><option>Fácil</option><option>Médio</option><option>Difícil</option></select></label></div><label>Enunciado<textarea required name="text" rows={5} placeholder="Digite o enunciado completo..."/></label><div className="options">{['a','b','c','d','e'].map(x=><label key={x}>{x.toUpperCase()}<input required name={x}/></label>)}</div><div className="grid"><label>Alternativa correta<select name="answer">{['A','B','C','D','E'].map((x,i)=><option key={x} value={i}>{x}</option>)}</select></label><label>Link da resolução no YouTube<input type="url" name="video" placeholder="https://youtube.com/watch?v=..."/></label><label>Documento de origem<input name="source" placeholder="Ex.: ITA 2026 - 1ª fase"/></label><label>Página original<input type="number" min="0" name="page"/></label></div><button className="primary">Publicar questão</button></form></section>}
 </main>
}
