export type Question = {
  id: number; code: string; year: number; number: number; topic: string; level: string;
  title: string; text: string; options: string[]; answer: number | null; answerLabel: string | null;
  status: string; video: string; scriptStatus: string; sourcePage: number; sourceFile: string;
  sourceImage: string; essentialFigure: boolean;
};

export const importedQuestions: Question[] = [
  {
    "id": 202613,
    "code": "ITA 2026 · Q13",
    "year": 2026,
    "number": 13,
    "topic": "Eletricidade",
    "level": "Difícil",
    "title": "Corrente em um feixe de elétrons",
    "text": "Em um microscópio eletrônico de varredura (MEV), um feixe de elétrons apresenta área transversal A, densidade de carga ρ e velocidade dos elétrons v. Sabendo que a corrente I do feixe é determinada pelo fluxo de carga através da seção reta e que C é uma constante adimensional, assinale a alternativa que representa a relação correta entre I, A, ρ e v.",
    "options": [
      "I = CρA²v.",
      "I = CρAv.",
      "I = CρAv².",
      "I = Cρv/A.",
      "I = CρA/v."
    ],
    "answer": 1,
    "answerLabel": "B",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 5,
    "sourceFile": "ITA 2026 - 1ª fase",
    "sourceImage": "/sources/ita-2026/page-05.png",
    "essentialFigure": false
  },
  {
    "id": 202614,
    "code": "ITA 2026 · Q14",
    "year": 2026,
    "number": 14,
    "topic": "Mecânica",
    "level": "Difícil",
    "title": "Encontro entre projétil e esfera",
    "text": "Uma pequena esfera é abandonada do repouso a partir de uma altura H, em relação ao solo, e cai verticalmente em queda livre. No mesmo instante em que a esfera inicia seu movimento, um canhão, situado a uma distância horizontal D da trajetória da esfera e a uma altura h relativamente ao solo, dispara um projétil com velocidade v, formando um ângulo θ em relação à horizontal. As condições são tais que o projétil atinge a esfera exatamente no instante em que ela toca o solo. Desprezando a resistência do ar e assumindo que a aceleração gravitacional é igual a g, assinale a alternativa que corresponde à magnitude da velocidade de lançamento v.",
    "options": [
      "v = √{[g/(2H)] [(H − h)² + D²]}.",
      "v = √{(g/H) [(H − h)² + D²]}.",
      "v = √{[g/(2H)] [(H − h)² − D²]}.",
      "v = √{(g/H) [(H − h)² − D²]}.",
      "v = √{(2g/H) [(H − h)² + D²]}."
    ],
    "answer": 0,
    "answerLabel": "A",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 5,
    "sourceFile": "ITA 2026 - 1ª fase",
    "sourceImage": "/sources/ita-2026/page-05.png",
    "essentialFigure": false
  },
  {
    "id": 202615,
    "code": "ITA 2026 · Q15",
    "year": 2026,
    "number": 15,
    "topic": "Mecânica",
    "level": "Difícil",
    "title": "Lançamento vertical com dissipação",
    "text": "Um objeto de massa m = 1,00 kg é lançado verticalmente para cima a partir do solo com velocidade inicial v₀ = 30,0 m/s. A força de resistência do ar tem módulo constante f_d = 2,00 N durante toda a trajetória. Ao retornar ao nível do solo, ele colide com uma plataforma de massa desprezível, presa a uma mola ideal vertical de constante elástica k = 800 N/m. Após o impacto, o sistema plataforma-massa desliza sobre apoios verticais, sofrendo uma força dissipativa total constante igual a 410 N. Assinale a alternativa que corresponde, respectivamente, à altura máxima atingida pelo objeto e ao valor que mais se aproxima da energia total dissipada até a mola atingir sua máxima compressão.",
    "options": [
      "45,0 m; 180 J.",
      "45,0 m; 376 J.",
      "37,5 m; 150 J.",
      "37,5 m; 355 J.",
      "37,5 m; 765 J."
    ],
    "answer": 3,
    "answerLabel": "D",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 5,
    "sourceFile": "ITA 2026 - 1ª fase",
    "sourceImage": "/sources/ita-2026/page-05.png",
    "essentialFigure": false
  },
  {
    "id": 202616,
    "code": "ITA 2026 · Q16",
    "year": 2026,
    "number": 16,
    "topic": "Gravitação",
    "level": "Difícil",
    "title": "Órbita de três planetas",
    "text": "Três planetas de massas m idênticas orbitam, em trajetória circular, uma estrela de massa M. A posição relativa entre os planetas, a cada instante, forma um triângulo equilátero de lado a, conforme mostrado na figura. Sabendo que G é a constante da gravitação universal, podemos afirmar que o período dessa órbita é dado por",
    "options": [
      "T = 2πa^(3/2)√3 / √[G(9M + 8m)].",
      "T = 2πa^(3/2) / √[G(M + 3m)].",
      "T = 2πa^(3/2) / √[3G(√3 M + m)].",
      "T = 2πa^(3/2) / √[G(3M + m)].",
      "T = 2πa^(3/2) / √[G(9M + √3 m)]."
    ],
    "answer": 2,
    "answerLabel": "C",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 6,
    "sourceFile": "ITA 2026 - 1ª fase",
    "sourceImage": "/sources/ita-2026/page-06.png",
    "essentialFigure": true
  },
  {
    "id": 202617,
    "code": "ITA 2026 · Q17",
    "year": 2026,
    "number": 17,
    "topic": "Oscilações",
    "level": "Difícil",
    "title": "Pêndulo e sistema massa-mola",
    "text": "Considere um pêndulo simples, com um fio ideal de comprimento ℓ sob ação da gravidade de aceleração g, e um sistema massa-mola na horizontal, com uma mola de comprimento natural x₀ e uma massa que desliza sobre uma superfície lisa, conforme a figura. Ambos os corpos, o do pêndulo e o do sistema massa-mola, possuem a mesma massa. No instante inicial, o pêndulo é solto do repouso a partir de um pequeno ângulo θ com a vertical, enquanto a massa do sistema massa-mola é solta também do repouso a partir de uma posição x₁, em que a mola se encontra comprimida. As duas massas colidem quando a mola atinge seu comprimento natural e quando o pêndulo está na vertical. Nesse instante, elas possuem a mesma velocidade. Assinale a alternativa que corresponde a relação entre o ângulo θ, de lançamento do pêndulo, e os outros parâmetros físicos relevantes.",
    "options": [
      "cos θ = 1 − (x₁ − x₀)²/(2ℓ²).",
      "sen θ = 1 − (x₁ − x₀)²/(2ℓ²).",
      "cos θ = 1 − (x₁ − x₀)²/ℓ².",
      "sen θ = 1 − 2ℓ²/(x₁ − x₀)².",
      "cos θ = 1 − ℓ²/(x₁ − x₀)²."
    ],
    "answer": 0,
    "answerLabel": "A",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 6,
    "sourceFile": "ITA 2026 - 1ª fase",
    "sourceImage": "/sources/ita-2026/page-06.png",
    "essentialFigure": true
  },
  {
    "id": 202618,
    "code": "ITA 2026 · Q18",
    "year": 2026,
    "number": 18,
    "topic": "Hidrostática",
    "level": "Difícil",
    "title": "Equilíbrio em vaso comunicante",
    "text": "Um vaso comunicante contém um volume V₀ = 2,00 L de água e possui duas colunas verticais conectadas por um tubo de conexão de comprimento L₀ = 10,0 cm e área de seção transversal A_c = 100 cm², conforme a figura. Sobre cada uma das colunas verticais, colocam-se duas massas distintas: m₁ = 200 g sobre a coluna de área A₁ = 100 cm² e m₂ = 100 g sobre a coluna de área A₂ = 400 cm². Admita que o sistema atinge o equilíbrio estático, que a água é incompressível e despreze o atrito. Dado o exposto, assinale a alternativa que corresponde à altura da coluna de água sob a massa m₁.",
    "options": [
      "6,00 cm.",
      "2,35 cm.",
      "1,75 cm.",
      "0,75 cm.",
      "0,60 cm."
    ],
    "answer": 4,
    "answerLabel": "E",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 7,
    "sourceFile": "ITA 2026 - 1ª fase",
    "sourceImage": "/sources/ita-2026/page-07.png",
    "essentialFigure": true
  },
  {
    "id": 202619,
    "code": "ITA 2026 · Q19",
    "year": 2026,
    "number": 19,
    "topic": "Termodinâmica",
    "level": "Difícil",
    "title": "Eficiência de ar-condicionado",
    "text": "Em um escritório, trabalham 10 funcionários de segunda a sexta, em um regime de oito horas por dia. Diariamente o ar-condicionado é ligado para manter o local de trabalho a 17 °C, sendo que o ambiente externo está a uma temperatura de 37 °C. Considere que o ar-condicionado funcione com máxima eficiência e que ele age apenas para retirar o calor gerado pelas pessoas, que é de 100 W por funcionário. Sabendo que a tarifa da energia elétrica é de R$ 0,91 por kWh, assinale o custo aproximado para usar o ar-condicionado durante 4 semanas.",
    "options": [
      "R$ 8,00.",
      "R$ 10,00.",
      "R$ 14,00.",
      "R$ 80,00.",
      "R$ 170,00."
    ],
    "answer": 1,
    "answerLabel": "B",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 7,
    "sourceFile": "ITA 2026 - 1ª fase",
    "sourceImage": "/sources/ita-2026/page-07.png",
    "essentialFigure": false
  },
  {
    "id": 202620,
    "code": "ITA 2026 · Q20",
    "year": 2026,
    "number": 20,
    "topic": "Óptica",
    "level": "Difícil",
    "title": "Interferência em filme de óleo",
    "text": "Um acidente marítimo causou um derramamento de óleo no mar. Na região, formou-se uma fina camada iridescente de óleo que flutua sobre a água calma do mar. Os índices de refração do óleo e da água são 3/2 e 4/3, respectivamente. Suponha que, à tarde, a luz solar incide com ângulo de 45° sobre a mancha de óleo e que um observador observa o reflexo do sol na camada de óleo com uma cor verde, com forte contribuição de comprimentos de onda em torno de 520 nm. Assinale a alternativa que contém o valor mais próximo da menor espessura da camada de óleo que permita a ocorrência do efeito descrito.",
    "options": [
      "40 nm.",
      "90 nm.",
      "100 nm.",
      "160 nm.",
      "200 nm."
    ],
    "answer": 2,
    "answerLabel": "C",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 7,
    "sourceFile": "ITA 2026 - 1ª fase",
    "sourceImage": "/sources/ita-2026/page-07.png",
    "essentialFigure": false
  },
  {
    "id": 202621,
    "code": "ITA 2026 · Q21",
    "year": 2026,
    "number": 21,
    "topic": "Eletricidade",
    "level": "Difícil",
    "title": "Potenciômetro e resistências",
    "text": "O circuito mostrado na figura é composto por um potenciômetro conectado a uma bateria de 12 V. Quando o cursor do potenciômetro é girado no sentido anti-horário, a resistência R1 tende a zero, e R2 atinge seu valor máximo; no sentido horário, ocorre o contrário. Um voltímetro ideal está conectado ao terminal central do potenciômetro, medindo a diferença de potencial entre esse ponto e o terminal negativo da bateria. Dois testes foram realizados nesse circuito. No Teste 1, uma resistência desconhecida R3 foi conectada, e a voltagem indicada pelo voltímetro foi registrada à medida que o cursor do potenciômetro era girado no sentido horário. No Teste 2, uma outra resistência desconhecida R4 substituiu a R3, e o procedimento foi repetido. O gráfico V × R1/R2 mostra os resultados obtidos nos dois testes. Com base no que foi apresentado, é possível afirmar que",
    "options": [
      "a resistência R4 é menor que a resistência R3.",
      "a corrente elétrica que passa por R3 é menor do que a que passa por R4, para qualquer posição do cursor do potenciômetro.",
      "a curva correspondente ficaria mais próxima à curva do Teste 1 do que à curva do Teste 2, se R3 e R4 fossem retiradas do circuito (este ramo ficaria aberto).",
      "os valores da voltagem da curva V × R1/R3 serão menores que os valores de voltagem da curva V × R1/R4 para os mesmos valores de abscissa admissíveis em ambos os casos.",
      "a razão entre as tensões indicadas nos Testes 2 e Teste 1 permanece constante e é exatamente igual à razão R4/R3, para qualquer posição do cursor do potenciômetro."
    ],
    "answer": 3,
    "answerLabel": "D",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 8,
    "sourceFile": "ITA 2026 - 1ª fase",
    "sourceImage": "/sources/ita-2026/page-08.png",
    "essentialFigure": true
  },
  {
    "id": 202622,
    "code": "ITA 2026 · Q22",
    "year": 2026,
    "number": 22,
    "topic": "Eletromagnetismo",
    "level": "Difícil",
    "title": "Ímã em tubo condutor perfurado",
    "text": "Considere um tubo cilíndrico condutor de raio R dividido em 3 regiões. Em cada região, há um conjunto de furos de raios distintos, a, b e c, igualmente espaçados. Um ímã é solto, partindo do repouso a partir do topo do cilindro, conforme apresentado na figura. Considere as seguintes afirmações:\n\nI. Se os raios a, b e c tendem a zero, a aceleração do ímã será a menor possível.\n\nII. Se os raios a = c < b, a aceleração do ímã em c será maior que em b.\n\nIII. Se os raios a = b > c, e considerando o efeito Joule no material condutor, a temperatura local em c é maior que em a e b.\n\nIV. Se os raios a = b = c, com a região b agora composta por um material dielétrico ideal, a velocidade final do ímã, após passar por c, será maior do que seria caso todo o tubo fosse condutor.\n\nV. Se todo o tubo fosse composto de um material dielétrico ideal com raios a > b > c, a aceleração em b seria maior que em c.\n\nEstão corretas apenas",
    "options": [
      "I, II e V.",
      "II, III e IV.",
      "III, IV e V.",
      "I, II, III e IV.",
      "I, III e IV."
    ],
    "answer": 4,
    "answerLabel": "E",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 9,
    "sourceFile": "ITA 2026 - 1ª fase",
    "sourceImage": "/sources/ita-2026/page-09.png",
    "essentialFigure": true
  },
  {
    "id": 202623,
    "code": "ITA 2026 · Q23",
    "year": 2026,
    "number": 23,
    "topic": "Ondulatória",
    "level": "Difícil",
    "title": "Ultrassom e pressão sanguínea",
    "text": "Uma das aplicações dos equipamentos de ultrassom na medicina é o auxílio no diagnóstico de doenças cardíacas. Com eles, é possível avaliar o fluxo sanguíneo que parte do coração e alcança artérias importantes do corpo. O aparelho opera em repouso, posicionado próximo a uma artéria específica, emitindo uma onda sonora de frequência f e velocidade v, que incide sobre o sangue da artéria. A onda incidente se propaga em sentido oposto ao fluxo de sangue, sendo refletida por ele e, posteriormente, captada pelo próprio equipamento. O dispositivo mede a diferença Δf entre a frequência registrada e a frequência de emissão. Considere que a artéria e o coração estão na mesma altura, que v_c é a velocidade do sangue no coração, que ρ é sua densidade e que a velocidade do sangue na artéria é muito menor que v. Assinale a alternativa que corresponde à expressão da variação da pressão sanguínea entre a artéria e o coração.",
    "options": [
      "(1/2)ρ[v_c² − (2vΔf/f)²].",
      "ρ[v_c² − (vΔf/2f)²].",
      "(1/2)ρ[v_c² − (vΔf/2f)²].",
      "ρ[2v_c² − (vΔf/f)²].",
      "(1/2)ρ[2v_c² − (vΔf/2f)²]."
    ],
    "answer": 2,
    "answerLabel": "C",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 9,
    "sourceFile": "ITA 2026 - 1ª fase",
    "sourceImage": "/sources/ita-2026/page-09.png",
    "essentialFigure": false
  },
  {
    "id": 202624,
    "code": "ITA 2026 · Q24",
    "year": 2026,
    "number": 24,
    "topic": "Física moderna",
    "level": "Difícil",
    "title": "Dupla fenda e resposta fotoelétrica",
    "text": "A figura a seguir ilustra um dispositivo D(λ,A), que emite radiação eletromagnética monocromática de comprimento de onda λ e intensidade A e que chega a um anteparo opaco S₁ com duas fendas. A radiação é detectada por um dispositivo de medição M fixado em um segundo anteparo S₂. Esse dispositivo M, ao ser submetido à radiação, gera uma resposta de corrente I em função da diferença de potencial V aplicada nos seus terminais. A figura também apresenta 4 gráficos I × V, todos na mesma escala, obtidos a partir de medições com diferentes valores de λ e A. É falsa a afirmação de que é possível passar da situação",
    "options": [
      "(2) para (1), apenas diminuindo A.",
      "(2) para (4), mudando λ e aumentando A.",
      "(2) para (3), aumentando apenas λ.",
      "(4) para (3), mudando apenas λ.",
      "(3) para (1), aumentando λ e diminuindo A."
    ],
    "answer": 2,
    "answerLabel": "C",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 10,
    "sourceFile": "ITA 2026 - 1ª fase",
    "sourceImage": "/sources/ita-2026/page-10.png",
    "essentialFigure": true
  },
  {
    "id": 202513,
    "code": "ITA 2025 · Q13",
    "year": 2025,
    "number": 13,
    "topic": "Mecânica",
    "level": "Difícil",
    "title": "Distância percorrida e velocidade média",
    "text": "Considere uma partícula cuja posição é dada pela função horária x(t) = √(D² + (Vt − D)²), em que V e D são constantes positivas, com unidades adequadas. Seja v̄(t) a velocidade média do móvel entre o instante inicial t₀ = 0 s e um instante arbitrário t. Assinale a alternativa que contém a distância percorrida pela partícula desde o início do movimento até o instante no qual v̄(t) = 0 m/s.",
    "options": [
      "(√2 − 1)D",
      "2(√2 − 1)D",
      "√2D",
      "2D",
      "2√2D"
    ],
    "answer": 1,
    "answerLabel": "B",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 5,
    "sourceFile": "ITA 2025 - 1ª fase",
    "sourceImage": "/sources/ita-2025/page-05.png",
    "essentialFigure": false
  },
  {
    "id": 202514,
    "code": "ITA 2025 · Q14",
    "year": 2025,
    "number": 14,
    "topic": "Mecânica",
    "level": "Difícil",
    "title": "Carrinho em trilho e colisão",
    "text": "Um carrinho realiza um percurso sobre um trilho em um plano vertical, como mostra a figura ao lado. Partindo do repouso no ponto A, ele percorre uma distância ℓ até o ponto B com aceleração constante a₀. Ao chegar ao ponto B, segue uma trajetória circular de raio R sob a ação da aceleração gravitacional até o ponto C. Então, passa a executar um movimento retilíneo uniforme. Ao chegar ao ponto D, realiza uma colisão perfeitamente inelástica com um outro carrinho de mesma massa. Desconsiderando efeitos de forças de atrito, assinale a alternativa que corresponde ao módulo da velocidade do carrinho após o choque.",
    "options": [
      "½√(2a₀ℓ + 4gR)",
      "√[½(a₀ℓ + gR)]",
      "√(a₀ℓ + 2gR)",
      "½√(a₀ℓ + 2gR)",
      "√[2(a₀ℓ + 2gR)]"
    ],
    "answer": 0,
    "answerLabel": "A",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 5,
    "sourceFile": "ITA 2025 - 1ª fase",
    "sourceImage": "/sources/ita-2025/page-05.png",
    "essentialFigure": true
  },
  {
    "id": 202515,
    "code": "ITA 2025 · Q15",
    "year": 2025,
    "number": 15,
    "topic": "Gravitação",
    "level": "Difícil",
    "title": "Órbita de um satélite natural",
    "text": "Um explorador em um planeta exótico, circundado por um satélite natural, observa que o intervalo de tempo entre as fases cheia e nova de seu satélite é de 58 dias terrestres. Sabe-se que a massa desse planeta é igual à massa da Terra e muito maior que a massa de seu satélite. Assinale a alternativa que contém a estimativa correta da distância entre o planeta exótico e seu satélite.",
    "options": [
      "8 × 10⁸ m",
      "1 × 10⁹ m",
      "2 × 10⁹ m",
      "4 × 10⁹ m",
      "6 × 10⁹ m"
    ],
    "answer": 1,
    "answerLabel": "B",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 6,
    "sourceFile": "ITA 2025 - 1ª fase",
    "sourceImage": "/sources/ita-2025/page-06.png",
    "essentialFigure": false
  },
  {
    "id": 202516,
    "code": "ITA 2025 · Q16",
    "year": 2025,
    "number": 16,
    "topic": "Oscilações",
    "level": "Difícil",
    "title": "Molas acopladas em série",
    "text": "Considere três osciladores massa-mola independentes (1, 2 e 3) de massa m e constantes elásticas k₁, k₂ e k₃, respectivamente. O tempo que o sistema massa-mola 1 leva para completar uma oscilação é igual ao tempo que o sistema massa-mola 2 leva para completar duas oscilações e ao tempo que o sistema massa-mola 3 leva para completar três oscilações. Agora considere um sistema composto por essas mesmas três molas acopladas em série e colocadas para oscilar junto a um objeto de massa 4m. Assinale a alternativa que contém o valor numérico mais próximo da razão entre a frequência do sistema massa-mola 1 e a frequência do sistema massa-mola em série.",
    "options": [
      "7,5",
      "3,8",
      "2,7",
      "2,3",
      "1,0"
    ],
    "answer": 3,
    "answerLabel": "D",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 6,
    "sourceFile": "ITA 2025 - 1ª fase",
    "sourceImage": "/sources/ita-2025/page-06.png",
    "essentialFigure": false
  },
  {
    "id": 202517,
    "code": "ITA 2025 · Q17",
    "year": 2025,
    "number": 17,
    "topic": "Hidrostática",
    "level": "Difícil",
    "title": "Barra parcialmente submersa",
    "text": "Uma barra homogênea e fina de seção reta circular A e comprimento L tem uma de suas extremidades fixas a uma articulação, podendo girar sem atrito. As figuras abaixo mostram duas situações nas quais a barra se encontra em equilíbrio estático. No primeiro caso, a barra está parcialmente mergulhada em uma cuba preenchida com um líquido, de forma que 25% de seu comprimento ficam submersos, conforme a figura (a). No segundo caso, um objeto pontual, com 50% da massa da barra, está fixado em sua extremidade livre, como ilustra a figura (b). Assinale a alternativa correspondente ao novo comprimento submerso da barra na situação exposta na figura (b).",
    "options": [
      "L(1 − √2/2)",
      "L(1 − √2/4)",
      "L/2",
      "3L/8",
      "3L/4"
    ],
    "answer": 1,
    "answerLabel": "B",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 6,
    "sourceFile": "ITA 2025 - 1ª fase",
    "sourceImage": "/sources/ita-2025/page-06.png",
    "essentialFigure": true
  },
  {
    "id": 202518,
    "code": "ITA 2025 · Q18",
    "year": 2025,
    "number": 18,
    "topic": "Termodinâmica",
    "level": "Difícil",
    "title": "Gás ideal, êmbolo e mola",
    "text": "Um recipiente de paredes diatérmicas é dividido ao meio por um êmbolo de área A. O lado esquerdo do êmbolo é conectado ao recipiente por uma mola ideal de constante elástica k, em uma região onde há vácuo. No lado direito do êmbolo, há um gás ideal a uma pressão inicial P₀. Então, uma quantidade Q de calor é transferida a esse gás por um processo reversível e isotérmico. Assinale a alternativa que fornece a diferença entre o comprimento natural da mola e o seu comprimento ao final do processo descrito.",
    "options": [
      "√(2Q/k)",
      "√(2Q/k) + P₀A/k",
      "√(Q/(2k)) + P₀A/k",
      "√[Q/k + (P₀A/k)²]",
      "√[2Q/k + (P₀A/k)²]"
    ],
    "answer": null,
    "answerLabel": null,
    "status": "Anulada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 7,
    "sourceFile": "ITA 2025 - 1ª fase",
    "sourceImage": "/sources/ita-2025/page-07.png",
    "essentialFigure": false
  },
  {
    "id": 202519,
    "code": "ITA 2025 · Q19",
    "year": 2025,
    "number": 19,
    "topic": "Ondulatória",
    "level": "Difícil",
    "title": "Amplificação em estetoscópio",
    "text": "O estetoscópio é um instrumento amplamente utilizado por profissionais de saúde para auscultar sons internos do corpo humano, como batimentos cardíacos e fluxo sanguíneo. Considere o modelo simplificado de um estetoscópio, ilustrado na figura, composto de um cone truncado de bases circulares, cuja base maior possui raio R₁, e a base menor, raio R₂. Nos cilindros, perfeitamente conectados em cada base, há pistões finos e rígidos de massa desprezível, que podem se mover para cima e para baixo sem atrito. Considere que a onda sonora atinge toda a superfície do pistão maior e que sua energia é transferida integralmente para o pistão menor. Assinale a alternativa que corresponde à amplificação, em dB, em função dos raios das extremidades do estetoscópio.",
    "options": [
      "2 log(R₁/R₂)",
      "4 log(R₁/R₂)",
      "20 log(R₁/R₂)",
      "40 log(R₁/R₂)",
      "80 log(R₁/R₂)"
    ],
    "answer": 2,
    "answerLabel": "C",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 7,
    "sourceFile": "ITA 2025 - 1ª fase",
    "sourceImage": "/sources/ita-2025/page-07.png",
    "essentialFigure": false
  },
  {
    "id": 202520,
    "code": "ITA 2025 · Q20",
    "year": 2025,
    "number": 20,
    "topic": "Óptica",
    "level": "Difícil",
    "title": "Formação do arco-íris",
    "text": "O arco-íris é um fenômeno meteorológico de grande beleza e com profundo simbolismo para diferentes culturas. Sua explicação física foi debatida desde a antiguidade até o início da idade moderna. A respeito desse fenômeno, são feitas as seguintes afirmações:\nI. Cada componente de comprimento de onda da luz do Sol que incide sobre uma gotícula de água suspensa na atmosfera emerge com o mesmo ângulo de espalhamento.\nII. Para a formação do arco-íris, são necessárias tanto a ocorrência de refração quanto a de reflexão da luz.\nIII. O efeito visual do arco-íris é resultado de a luz do Sol ser policromática e de a água ser um meio dispersivo na faixa do espectro eletromagnético visível.\nEstá(ão) correta(s):",
    "options": [
      "apenas I.",
      "apenas I e II.",
      "apenas I e III.",
      "apenas II e III.",
      "I, II e III."
    ],
    "answer": 3,
    "answerLabel": "D",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 8,
    "sourceFile": "ITA 2025 - 1ª fase",
    "sourceImage": "/sources/ita-2025/page-08.png",
    "essentialFigure": false
  },
  {
    "id": 202521,
    "code": "ITA 2025 · Q21",
    "year": 2025,
    "number": 21,
    "topic": "Eletrostática",
    "level": "Difícil",
    "title": "Capacitor com água e óleo",
    "text": "Considere um tanque cúbico metálico de lado L + a (L ≫ a), aberto no topo, preenchido com água e óleo. O tanque contém, no seu interior, um cubo metálico de lado L, com 5 de seus lados totalmente submersos e o outro emerso na superfície, centralizado com a face aberta do tanque. Uma diferença de potencial de V é estabelecida entre o cubo e o tanque, de forma que o sistema atue como um capacitor. A vista frontal do sistema encontra-se ilustrada na figura ao lado. Sabe-se que o óleo possui uma densidade de dₒ = 0,90 g/cm³ e constante dielétrica κₒ, que a água tem uma densidade igual a dₐ = 1,0 g/cm³ e constante dielétrica κₐ e que a densidade do cubo é d_c = 0,92 g/cm³. Desconsiderando efeitos de borda, assinale a alternativa que fornece a capacitância do sistema.",
    "options": [
      "(ε₀L²/a)(6,4κₒ + 2,6κₐ)",
      "(ε₀L²/a)(6,4κₒ + 1,6κₐ)",
      "(ε₀L²/a)(3,2κₒ + 0,8κₐ)",
      "(ε₀L²/a)(3,2κₒ + 1,8κₐ)",
      "(ε₀L²/a)(1,6κₒ + 6,4κₐ)"
    ],
    "answer": 0,
    "answerLabel": "A",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 8,
    "sourceFile": "ITA 2025 - 1ª fase",
    "sourceImage": "/sources/ita-2025/page-08.png",
    "essentialFigure": true
  },
  {
    "id": 202522,
    "code": "ITA 2025 · Q22",
    "year": 2025,
    "number": 22,
    "topic": "Eletricidade",
    "level": "Difícil",
    "title": "Ponte resistiva e reostato",
    "text": "Com o intuito de medir a resistência elétrica de um resistor Rₓ, foi montado o circuito mostrado na figura. Nesse circuito, sabe-se que os resistores R₁ e R₃ possuem resistências de 20 Ω e 30 Ω, respectivamente, e que R₂ é um reostato cuja resistência pode variar de 0 a 100 Ω. Foi feito um experimento em que, à medida que a resistência R₂ era variada, a voltagem entre os pontos C e B era medida por um voltímetro V. Os resultados das medições estão apresentados no gráfico. Sabendo que a tensão da fonte é contínua e possui um valor de 12,0 V, assinale a alternativa que corresponde ao valor aproximado da resistência elétrica Rₓ.",
    "options": [
      "4 Ω",
      "10 Ω",
      "12 Ω",
      "20 Ω",
      "50 Ω"
    ],
    "answer": 1,
    "answerLabel": "B",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 9,
    "sourceFile": "ITA 2025 - 1ª fase",
    "sourceImage": "/sources/ita-2025/page-09.png",
    "essentialFigure": true
  },
  {
    "id": 202523,
    "code": "ITA 2025 · Q23",
    "year": 2025,
    "number": 23,
    "topic": "Eletromagnetismo",
    "level": "Difícil",
    "title": "Indução em uma circunferência",
    "text": "Um campo magnético diminui ao longo do tempo a uma taxa fixa de (20î − 10ĵ + 12k̂) T/s. Considere uma circunferência feita com material cuja resistência por unidade de comprimento vale 3 Ω/m e que passa pela origem e pelos pontos (4 m, 0 m, 0 m) e (2 m, 2 m, 0 m). Assinale a alternativa que corresponde ao valor da corrente que flui pela circunferência.",
    "options": [
      "2,0 A",
      "3,3 A",
      "4,0 A",
      "6,7 A",
      "8,5 A"
    ],
    "answer": 2,
    "answerLabel": "C",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 9,
    "sourceFile": "ITA 2025 - 1ª fase",
    "sourceImage": "/sources/ita-2025/page-09.png",
    "essentialFigure": false
  },
  {
    "id": 202524,
    "code": "ITA 2025 · Q24",
    "year": 2025,
    "number": 24,
    "topic": "Física moderna",
    "level": "Difícil",
    "title": "Espalhamento Raman",
    "text": "O efeito Raman ocorre quando há o espalhamento inelástico da luz pela matéria, de forma que o fóton espalhado contém um pequeno decremento ou incremento de um quantum de energia relacionado a transições entre modos vibracionais na matéria. Em um experimento realizado a temperatura ambiente, um fóton incidente de comprimento de onda de 620 nm é espalhado por um cristal, resultando em um fóton espalhado com comprimento de onda de 590 nm. Suponha que esse mesmo cristal, submetido à mesma radiação incidente, seja mantido a uma temperatura próxima ao zero absoluto, de tal forma que somente um modo vibracional esteja envolvido no espalhamento inelástico. Assinale a alternativa que corresponde ao comprimento de onda do fóton espalhado.",
    "options": [
      "565 nm",
      "590 nm",
      "602 nm",
      "640 nm",
      "653 nm"
    ],
    "answer": 4,
    "answerLabel": "E",
    "status": "Importada",
    "video": "",
    "scriptStatus": "Pendente",
    "sourcePage": 9,
    "sourceFile": "ITA 2025 - 1ª fase",
    "sourceImage": "/sources/ita-2025/page-09.png",
    "essentialFigure": false
  }
];
